import { useState } from 'react';
import { recordAviationAuditEvent } from '../../services/aviationAuditService';
import { getAviationStakeholderDecisions, saveAviationStakeholderDecision, updateAviationStakeholderDecision, type AviationStakeholderDecision, type AviationStakeholderDecisionType } from '../../services/aviationPilotExecutionService';

export function AviationStakeholderDecisionLog({ actorRole }: { actorRole: string }) {
  const [decisions, setDecisions] = useState(getAviationStakeholderDecisions());
  const [decisionDate, setDecisionDate] = useState(new Date().toISOString().slice(0, 10));
  const [decisionType, setDecisionType] = useState<AviationStakeholderDecisionType>('approved_data_source');
  const [stakeholderRole, setStakeholderRole] = useState('Aviation / Global Security');
  const [title, setTitle] = useState('NOAA first live integration decision');
  const [summary, setSummary] = useState('');
  const [affectedArea, setAffectedArea] = useState('NOAA Weather Data');
  const [owner, setOwner] = useState('Aviation IT / FPI Engineering');
  function submit() { if (!title.trim()) return; const saved = saveAviationStakeholderDecision({ decision_date: decisionDate, decision_type: decisionType, stakeholder_role: stakeholderRole, title, decision_summary: summary, affected_area: affectedArea, follow_up_owner: owner, due_date: null, status: 'open' }); recordAviationAuditEvent({ event_type: 'stakeholder_decision_logged', actor_role: actorRole, summary: `Stakeholder decision logged: ${saved.title}` }); setDecisions(getAviationStakeholderDecisions()); setSummary(''); }
  function updateStatus(id: string, status: AviationStakeholderDecision['status']) { updateAviationStakeholderDecision(id, { status }); recordAviationAuditEvent({ event_type: 'stakeholder_decision_logged', actor_role: actorRole, summary: `Stakeholder decision status updated: ${id} to ${status}` }); setDecisions(getAviationStakeholderDecisions()); }
  return <section className="panel aviation-panel"><div className="card-heading"><div><p className="eyebrow">Stakeholder governance</p><h3>Decision Log</h3></div></div><div className="aviation-detail-grid"><input className="aviation-input" type="date" value={decisionDate} onChange={(event) => setDecisionDate(event.target.value)} /><select className="aviation-input" value={decisionType} onChange={(event) => setDecisionType(event.target.value as AviationStakeholderDecisionType)}><option value="approved_data_source">approved_data_source</option><option value="rejected_data_source">rejected_data_source</option><option value="role_access_decision">role_access_decision</option><option value="governance_decision">governance_decision</option><option value="production_blocker">production_blocker</option><option value="integration_priority_change">integration_priority_change</option></select><input className="aviation-input" value={stakeholderRole} onChange={(event) => setStakeholderRole(event.target.value)} /></div><input className="aviation-input" placeholder="Decision title" value={title} onChange={(event) => setTitle(event.target.value)} /><textarea className="aviation-input" placeholder="Decision summary" value={summary} onChange={(event) => setSummary(event.target.value)} /><div className="aviation-detail-grid"><input className="aviation-input" placeholder="Affected area" value={affectedArea} onChange={(event) => setAffectedArea(event.target.value)} /><input className="aviation-input" placeholder="Follow-up owner" value={owner} onChange={(event) => setOwner(event.target.value)} /></div><button className="ops-action-button" onClick={submit}>Record Decision</button><div className="aviation-table-wrap"><table className="aviation-table"><thead><tr><th>Date</th><th>Type</th><th>Title</th><th>Affected Area</th><th>Owner</th><th>Status</th></tr></thead><tbody>{decisions.map((decision) => <tr key={decision.decision_id}><td>{decision.decision_date}</td><td>{decision.decision_type}</td><td>{decision.title}</td><td>{decision.affected_area}</td><td>{decision.follow_up_owner}</td><td><select className="aviation-input" value={decision.status} onChange={(event) => updateStatus(decision.decision_id, event.target.value as AviationStakeholderDecision['status'])}><option>open</option><option>accepted</option><option>superseded</option><option>closed</option></select></td></tr>)}</tbody></table></div></section>;
}
