import { useState } from 'react';
import { recordAviationAuditEvent } from '../../services/aviationAuditService';
import { createAviationPilotIssue, getAviationPilotIssues, updateAviationPilotIssue, type AviationPilotIssue } from '../../services/aviationPilotIssueService';

export function AviationPilotIssueTracker({ actorRole }: { actorRole: string }) {
  const [issues, setIssues] = useState(getAviationPilotIssues());
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState<AviationPilotIssue['category']>('ux_improvement');
  const [priority, setPriority] = useState<AviationPilotIssue['priority']>('medium');
  const [ownerRole, setOwnerRole] = useState('FPI / Aviation Product');
  function create() { if (!title.trim()) return; const issue = createAviationPilotIssue({ source_feedback_id: null, title, description, category, priority, owner_role: ownerRole, status: 'open' }); recordAviationAuditEvent({ event_type: 'pilot_issue_created', actor_role: actorRole, summary: `Pilot issue created: ${issue.title}` }); setTitle(''); setDescription(''); setIssues(getAviationPilotIssues()); }
  function update(issueId: string, updates: Partial<AviationPilotIssue>) { updateAviationPilotIssue(issueId, updates); recordAviationAuditEvent({ event_type: 'pilot_issue_updated', actor_role: actorRole, summary: `Pilot issue updated: ${issueId}` }); setIssues(getAviationPilotIssues()); }
  return <section className="panel aviation-panel"><div className="card-heading"><div><p className="eyebrow">Pilot issue tracker</p><h3>Actionable Issues</h3></div></div><input className="aviation-input" placeholder="Issue title" value={title} onChange={(e) => setTitle(e.target.value)} /><textarea className="aviation-input" placeholder="Description" value={description} onChange={(e) => setDescription(e.target.value)} /><div className="aviation-detail-grid"><select className="aviation-input" value={category} onChange={(e) => setCategory(e.target.value as AviationPilotIssue['category'])}><option value="bug">bug</option><option value="data_gap">data_gap</option><option value="integration_request">integration_request</option><option value="ux_improvement">ux_improvement</option><option value="governance">governance</option><option value="authorization">authorization</option><option value="risk_model">risk_model</option><option value="briefing">briefing</option><option value="other">other</option></select><select className="aviation-input" value={priority} onChange={(e) => setPriority(e.target.value as AviationPilotIssue['priority'])}><option>low</option><option>medium</option><option>high</option><option>critical</option></select><input className="aviation-input" value={ownerRole} onChange={(e) => setOwnerRole(e.target.value)} /></div><button className="ops-action-button" onClick={create}>Create Issue</button><div className="aviation-table-wrap"><table className="aviation-table"><thead><tr><th>Priority</th><th>Category</th><th>Title</th><th>Owner</th><th>Status</th></tr></thead><tbody>{issues.map((issue) => <tr key={issue.issue_id}><td>{issue.priority}</td><td>{issue.category}</td><td>{issue.title}</td><td>{issue.owner_role}</td><td><select className="aviation-input" value={issue.status} onChange={(e) => update(issue.issue_id, { status: e.target.value as AviationPilotIssue['status'] })}><option>open</option><option>in_progress</option><option>blocked</option><option>resolved</option><option>deferred</option></select></td></tr>)}</tbody></table></div></section>;
}
