import { useState } from 'react';
import { moveAviationTabDown, moveAviationTabUp, resetAviationTabPreferences, saveAviationTabPreferences, setAviationTabVisibility, type AviationAvailableTab, type AviationTabPreferences } from '../../services/aviationTabPreferenceService';

export function AviationTabSettings({ availableTabs, preferences, onClose, onPreferencesChange }: { availableTabs: AviationAvailableTab[]; preferences: AviationTabPreferences; onClose: () => void; onPreferencesChange: (preferences: AviationTabPreferences) => void }) {
  const [draft, setDraft] = useState(preferences);
  const availableById = new Map(availableTabs.map((tab) => [tab.tab_id, tab]));
  function saveAndClose() { saveAviationTabPreferences(draft); onPreferencesChange(draft); onClose(); }
  function resetDefaults() { if (!window.confirm('Reset Aviation tabs to the default layout?')) return; const defaults = resetAviationTabPreferences(availableTabs); setDraft(defaults); onPreferencesChange(defaults); }
  return <div className="side-panel-settings-backdrop" role="presentation"><section className="side-panel-settings-modal aviation-tab-settings-modal" role="dialog" aria-modal="true" aria-labelledby="aviation-tab-settings-title"><div className="card-heading"><div><p className="eyebrow">Aviation workspace</p><h2 id="aviation-tab-settings-title">Customize Aviation Tabs</h2><p className="side-panel-settings-note">Show, hide, or reorder Aviation sub-tabs. At least one operational tab remains visible. RBAC still restricts Admin/Governance controls.</p></div><button className="ops-action-button secondary" onClick={onClose}>Close</button></div><div className="side-panel-settings-list">{draft.tabs.map((tab) => { const available = availableById.get(tab.tab_id); if (!available) return null; const index = draft.tabs.findIndex((item) => item.tab_id === tab.tab_id); return <article className="side-panel-settings-row" key={tab.tab_id}><div><div className="side-panel-row-title"><strong>{tab.label}</strong><span className="mode-pill">{available.operational ? 'Operational' : 'Admin / Support'}</span></div><p>{available.operational ? 'Core aviation operations workflow tab.' : 'Pilot, reporting, or admin support tab. Visibility does not grant restricted controls.'}</p></div><div className="side-panel-row-actions"><label className="side-panel-visible-toggle"><input type="checkbox" checked={tab.visible} onChange={(event) => setDraft(setAviationTabVisibility(draft, availableTabs, tab.tab_id, event.target.checked))} /> Visible</label><button className="ops-action-button secondary" disabled={index <= 0} onClick={() => setDraft(moveAviationTabUp(draft, tab.tab_id))}>Move Up</button><button className="ops-action-button secondary" disabled={index === draft.tabs.length - 1} onClick={() => setDraft(moveAviationTabDown(draft, tab.tab_id))}>Move Down</button></div></article>; })}</div><div className="side-panel-settings-footer"><button className="ops-action-button secondary" onClick={resetDefaults}>Reset to Default</button><button className="ops-action-button" onClick={saveAndClose}>Save Aviation Tabs</button></div></section></div>;
}
