import { useState } from 'react';
import { recordAviationAuditEvent } from '../../services/aviationAuditService';
import { getAviationFeedback, saveAviationFeedback, updateAviationFeedbackStatus, type AviationPilotFeedback } from '../../services/aviationFeedbackService';
import { createAviationPilotIssue } from '../../services/aviationPilotIssueService';

export function AviationPilotFeedbackPanel({ actorRole, tripId = null }: { actorRole: string; tripId?: string | null }) {
  const [category, setCategory] = useState<AviationPilotFeedback['category']>('usability');
  const [severity, setSeverity] = useState<AviationPilotFeedback['severity']>('medium');
  const [summary, setSummary] = useState('');
  const [details, setDetails] = useState('');
  const [suggestedChange, setSuggestedChange] = useState('');
  const [items, setItems] = useState(getAviationFeedback());
  function submit() { if (!summary.trim()) return; const saved = saveAviationFeedback({ actor_role: actorRole, trip_id: tripId, category, severity, summary, details, suggested_change: suggestedChange, status: 'new' }); recordAviationAuditEvent({ event_type: 'pilot_feedback_submitted', actor_role: actorRole, trip_id: tripId, summary: `Pilot feedback submitted: ${saved.summary}` }); setSummary(''); setDetails(''); setSuggestedChange(''); setItems(getAviationFeedback()); }
  function setStatus(id: string, status: AviationPilotFeedback['status']) { updateAviationFeedbackStatus(id, status); setItems(getAviationFeedback()); }
  function issueFrom(feedback: AviationPilotFeedback) { const issue = createAviationPilotIssue({ source_feedback_id: feedback.feedback_id, title: feedback.summary, description: feedback.details || feedback.summary, category: feedback.category === 'data_accuracy' ? 'data_gap' : feedback.category === 'risk_scoring' ? 'risk_model' : feedback.category === 'brief_quality' ? 'briefing' : feedback.category === 'authorization' ? 'authorization' : 'ux_improvement', priority: feedback.severity, owner_role: 'FPI / Aviation Product', status: 'open' }); recordAviationAuditEvent({ event_type: 'pilot_issue_created', actor_role: actorRole, trip_id: feedback.trip_id, summary: `Pilot issue created from feedback: ${issue.title}` }); }
  return <section className="panel aviation-panel"><div className="card-heading"><div><p className="eyebrow">Pilot feedback</p><h3>Stakeholder Feedback Capture</h3></div></div><div className="aviation-detail-grid"><select className="aviation-input" value={category} onChange={(e) => setCategory(e.target.value as AviationPilotFeedback['category'])}><option value="usability">usability</option><option value="data_accuracy">data_accuracy</option><option value="risk_scoring">risk_scoring</option><option value="brief_quality">brief_quality</option><option value="workflow">workflow</option><option value="authorization">authorization</option><option value="integration">integration</option><option value="other">other</option></select><select className="aviation-input" value={severity} onChange={(e) => setSeverity(e.target.value as AviationPilotFeedback['severity'])}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></div><input className="aviation-input" placeholder="Feedback summary" value={summary} onChange={(e) => setSummary(e.target.value)} /><textarea className="aviation-input" placeholder="Details" value={details} onChange={(e) => setDetails(e.target.value)} /><input className="aviation-input" placeholder="Suggested change" value={suggestedChange} onChange={(e) => setSuggestedChange(e.target.value)} /><button type="button" className="ops-action-button" onClick={submit}>Submit Feedback</button><div className="aviation-table-wrap"><table className="aviation-table"><thead><tr><th>When</th><th>Category</th><th>Severity</th><th>Summary</th><th>Status</th><th>Issue</th></tr></thead><tbody>{items.map((item) => <tr key={item.feedback_id}><td>{new Date(item.timestamp).toLocaleString()}</td><td>{item.category}</td><td>{item.severity}</td><td>{item.summary}</td><td><select className="aviation-input" value={item.status} onChange={(e) => setStatus(item.feedback_id, e.target.value as AviationPilotFeedback['status'])}><option>new</option><option>reviewed</option><option>accepted</option><option>rejected</option><option>implemented</option></select></td><td><button className="ops-action-button secondary" onClick={() => issueFrom(item)}>Create issue</button></td></tr>)}</tbody></table></div></section>;
}
