import { getAviationPilotConfig } from '../../services/aviationPilotConfig';

const stakeholderGroups = ['Walmart Aviation leadership and dispatch stakeholders', 'Executive Protection operations', 'Global Security / FPI leadership', 'Field Security pilot reviewers', 'FPI product and engineering', 'IT, Security, Privacy, and IAM reviewers'];
const demoScript = ['Open Aviation Travel Readiness and review Controlled Pilot Mode banner.', 'Launch the Executive Regional Airport Trip demo.', 'Search for a regional airport and run a facility radius scan.', 'Review map, nearby facilities, FAA/NOAA seeded panels, and risk explanation.', 'Generate readiness actions and a trip brief.', 'Save the trip, open detail view, run validation, and close with notes.', 'Submit feedback, create an issue, and record UAT results.', 'Review integration decision matrix and NOAA live readiness.', 'Generate pilot readout report and discuss go/no-go recommendation.'];
const uatTasks = ['Verify airport search supports major and regional airports.', 'Verify radius scanning returns explainable facility matches.', 'Verify seeded FAA/NOAA fallback is clearly labeled.', 'Verify risk score drivers are understandable.', 'Verify role restrictions hide EP-sensitive data.', 'Verify brief export/copy/print works.', 'Verify feedback, issues, UAT, decisions, and audit events persist locally.', 'Verify no live API calls occur unless provider mode is live_api.'];
const requiredDecisions = ['Approve or reject NOAA as first live data source.', 'Confirm source refresh cadence and fallback rules.', 'Confirm role access model for pilot and limited production.', 'Decide production persistence and audit logging targets.', 'Confirm whether pilot can move to limited production pilot.'];

export function AviationStakeholderPilotPlanPanel() {
  const config = getAviationPilotConfig();
  return <section className="panel aviation-panel"><div className="card-heading"><div><p className="eyebrow">Stakeholder pilot execution</p><h3>Stakeholder Pilot Plan</h3></div><span className="mode-pill">{config.environment_mode}</span></div><div className="aviation-detail-grid"><article className="aviation-selected-card"><span className="eyebrow">Objectives</span><ul>{config.pilot_success_criteria.map((item) => <li key={item}>{item}</li>)}</ul></article><article className="aviation-selected-card"><span className="eyebrow">Stakeholder Groups</span><ul>{stakeholderGroups.map((item) => <li key={item}>{item}</li>)}</ul></article></div><section className="aviation-detail-grid"><article className="aviation-selected-card"><span className="eyebrow">Demo Script</span><ol>{demoScript.map((item) => <li key={item}>{item}</li>)}</ol></article><article className="aviation-selected-card"><span className="eyebrow">UAT Tasks</span><ul>{uatTasks.map((item) => <li key={item}>{item}</li>)}</ul></article><article className="aviation-selected-card"><span className="eyebrow">Required Decisions</span><ul>{requiredDecisions.map((item) => <li key={item}>{item}</li>)}</ul></article></section><p className="aviation-caveat">Pilot remains advisory-only. Seeded/demo mode stays available for demos, UAT repeatability, fallback, and non-production reviews.</p></section>;
}
