type IntegrationRow = { source: string; owner: string; approval: string; technical: string; sensitivity: string; priority: string; blockers: string; nextAction: string };
const rows: IntegrationRow[] = [
  { source: 'NOAA Weather', owner: 'Aviation IT / FPI Engineering', approval: 'Pending approval', technical: 'Stub ready; provider-gated', sensitivity: 'Low/Moderate', priority: '1 - Recommended first live source', blockers: 'Approved endpoint, rate limits, caching and attribution rules', nextAction: 'Confirm NOAA endpoint/config and pilot approval decision.' },
  { source: 'FAA / NOTAM', owner: 'Aviation IT', approval: 'Not approved', technical: 'Stub ready; seeded fallback', sensitivity: 'Moderate', priority: '2', blockers: 'Approved NOTAM source and usage terms', nextAction: 'Identify sanctioned FAA/NOTAM data provider.' },
  { source: 'Walmart Facility Master', owner: 'Facility Data Product', approval: 'Not approved', technical: 'Adapter stub ready', sensitivity: 'Internal', priority: '3', blockers: 'Data owner, schema, refresh cadence', nextAction: 'Confirm facility master API/file feed and fields.' },
  { source: 'FPI Risk Posture', owner: 'FPI Product / Risk Data', approval: 'Not approved', technical: 'Seeded model ready', sensitivity: 'Sensitive internal', priority: '4', blockers: 'Risk data governance and scoring sign-off', nextAction: 'Map approved FPI posture source to risk inputs.' },
  { source: 'EP Readiness', owner: 'Executive Protection', approval: 'Not approved', technical: 'Seeded fields only', sensitivity: 'High', priority: '5', blockers: 'Sensitive EP data policy and access controls', nextAction: 'Define minimum safe pilot fields.' },
  { source: 'Incident Data', owner: 'Global Security / Safety', approval: 'Not approved', technical: 'Unavailable placeholder', sensitivity: 'High', priority: '6', blockers: 'Data classification and source ownership', nextAction: 'Identify approved incident/safety source.' },
  { source: 'Routing / Drive Time', owner: 'Platform Engineering', approval: 'Not approved', technical: 'Estimate service ready', sensitivity: 'Low', priority: '7', blockers: 'Routing provider and cost controls', nextAction: 'Select approved routing provider.' },
  { source: 'Persistence', owner: 'App Platform', approval: 'Not approved', technical: 'localStorage pilot mode', sensitivity: 'Moderate/High', priority: 'Required before production', blockers: 'Database/service selection and retention policy', nextAction: 'Choose production persistence layer.' },
  { source: 'Audit Logging', owner: 'Security Engineering', approval: 'Not approved', technical: 'localStorage audit events', sensitivity: 'Moderate', priority: 'Required before production', blockers: 'Enterprise logging target and schema', nextAction: 'Map audit events to production service.' },
  { source: 'Identity / IAM', owner: 'IAM / Security', approval: 'Not approved', technical: 'Local role selector only', sensitivity: 'High', priority: 'Required before production', blockers: 'Production role claims and access policy', nextAction: 'Integrate enterprise identity provider.' },
];

export function AviationLiveIntegrationDecisionMatrix() {
  return <section className="panel aviation-panel aviation-table-panel"><div className="card-heading"><div><p className="eyebrow">First live integration readiness</p><h3>Live Integration Decision Matrix</h3></div></div><div className="aviation-table-wrap"><table className="aviation-table"><thead><tr><th>Source</th><th>Owner</th><th>Approval</th><th>Technical readiness</th><th>Sensitivity</th><th>Priority</th><th>Blockers</th><th>Next action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.source}><td><strong>{row.source}</strong></td><td>{row.owner}</td><td>{row.approval}</td><td>{row.technical}</td><td>{row.sensitivity}</td><td>{row.priority}</td><td>{row.blockers}</td><td>{row.nextAction}</td></tr>)}</tbody></table></div><p className="aviation-caveat">Decision matrix is pilot planning support only; it does not enable live APIs or change provider modes.</p></section>;
}
