import { useEffect, useState } from 'react';
import { getAviationAuditEvents, recordAviationAuditEvent } from '../../services/aviationAuditService';
import { getAviationFeedback } from '../../services/aviationFeedbackService';
import { getAviationPilotIssues } from '../../services/aviationPilotIssueService';
import { getSavedTripPlans } from '../../services/aviationTripStorageService';

export function AviationPilotMetricsPanel() {
  const [metrics, setMetrics] = useState<Record<string, number>>({});
  useEffect(() => { async function load() { const trips = await getSavedTripPlans(); const audits = getAviationAuditEvents(); const feedback = getAviationFeedback(); const issues = getAviationPilotIssues(); const actions = trips.flatMap((trip) => trip.readiness_actions); const avg = (values: number[]) => values.length ? Math.round(values.reduce((a, b) => a + b, 0) / values.length) : 0; setMetrics({ 'Trips created': trips.length, 'Trips reviewed': trips.filter((trip) => trip.status === 'reviewed').length, 'Trips closed': trips.filter((trip) => trip.closure_summary || trip.status === 'closed').length, 'Briefs generated': audits.filter((event) => event.event_type === 'trip_brief_generated').length, 'Briefs exported': audits.filter((event) => event.event_type === 'brief_exported').length, 'Readiness actions generated': actions.length, 'Readiness actions closed': actions.filter((action) => action.status === 'Closed' || action.status === 'Verified').length, 'High-risk trips': trips.filter((trip) => ['High', 'Critical'].includes(trip.risk_band)).length, 'Demo scenario launches': audits.filter((event) => event.event_type === 'demo_scenario_launched').length, 'Feedback items submitted': feedback.length, 'Open pilot issues': issues.filter((issue) => ['open', 'in_progress', 'blocked'].includes(issue.status)).length, 'Missing data warnings': audits.filter((event) => event.event_type === 'data_validation_completed' && event.summary.includes('failure')).length, 'Average trip risk score': avg(trips.map((trip) => trip.risk_score)), 'Average confidence score': avg(trips.map((trip) => trip.confidence)) }); recordAviationAuditEvent({ event_type: 'pilot_metric_viewed', actor_role: 'system', summary: 'Pilot metrics dashboard viewed.' }); } load(); }, []);
  const entries = Object.entries(metrics);
  return <section className="panel aviation-panel"><div className="card-heading"><div><p className="eyebrow">Pilot outcomes</p><h3>Metrics Dashboard</h3></div></div>{entries.length === 0 ? <p className="aviation-empty">No local pilot metrics available yet.</p> : <div className="aviation-detail-grid">{entries.map(([label, value]) => <article className="aviation-selected-card" key={label}><span className="eyebrow">{label}</span><strong>{value}</strong></article>)}</div>}</section>;
}
