import { FAAWatchPanel } from './FAAWatchPanel';
import { WeatherRiskPanel } from './WeatherRiskPanel';
import { getAviationProvider } from '../../services/aviationProviderConfig';
import type { FAAProviderResult } from '../../services/faaService';
import type { WeatherProviderResult } from '../../services/weatherService';
import type { Airport, FacilityWithDistance } from '../../types/aviation';

export function AviationAlertsIntelligence({ airport, faaResult, weatherResult, facilities }: { airport: Airport | null; faaResult: FAAProviderResult; weatherResult: WeatherProviderResult; facilities: FacilityWithDistance[] }) {
  const faaProvider = getAviationProvider('faaProvider');
  const weatherProvider = getAviationProvider('weatherProvider');
  const incidentProvider = getAviationProvider('incidentProvider');
  const highRiskFacilities = facilities.filter((facility) => ['High', 'Critical'].includes(facility.facility_risk_band));
  return <div className="aviation-alerts-page"><section className="aviation-two-column"><FAAWatchPanel result={faaResult} /><WeatherRiskPanel result={weatherResult} /></section><section className="aviation-two-column"><article className="panel aviation-panel"><div className="card-heading"><div><p className="eyebrow">Airport operational notes</p><h3>{airport?.airport_name ?? 'No airport selected'}</h3></div></div>{airport ? <p>Status {airport.status}. Source freshness: {airport.source_freshness}. Last updated: {airport.last_updated}.</p> : <p className="aviation-empty">No selected airport. Select an airport to review airport notes.</p>}</article><article className="panel aviation-panel"><div className="card-heading"><div><p className="eyebrow">Source freshness</p><h3>FAA / NOAA / Incident</h3></div></div><p><span className={`aviation-badge aviation-badge-${faaProvider.mode}`}>{faaProvider.mode}</span> FAA: {faaProvider.status}</p><p><span className={`aviation-badge aviation-badge-${weatherProvider.mode}`}>{weatherProvider.mode}</span> NOAA: {weatherProvider.status}</p><p><span className={`aviation-badge aviation-badge-${incidentProvider.mode}`}>{incidentProvider.mode}</span> Incident: {incidentProvider.status}</p></article></section><section className="panel aviation-panel"><div className="card-heading"><div><p className="eyebrow">Facility intelligence signals</p><h3>Nearby Facility Risk Watch</h3></div></div>{highRiskFacilities.length === 0 ? <p className="aviation-empty">No high or critical nearby facility risk signals in the active scan.</p> : highRiskFacilities.map((facility) => <article key={facility.facility_id} className="aviation-alert-card"><strong>{facility.facility_risk_band}: {facility.facility_name}</strong><span>{facility.city}, {facility.state} • {facility.distance_miles.toFixed(1)} mi • {facility.top_risk_driver}</span><small>Source: {facility.source_freshness}</small></article>)}</section><section className="panel aviation-panel"><div className="card-heading"><div><p className="eyebrow">Incident / Safety Signals</p><h3>Not Connected</h3></div></div><p className="aviation-empty">Incident/safety provider is not connected. This signal is unavailable unless an approved source is identified and enabled through provider config.</p></section></div>;
}
